// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDR5-Fn4x6fbD2-JuNBuJ2BSXKJwSMxFT4',
    appId: '1:838989928746:web:3a330eba97264ea5352653',
    messagingSenderId: '838989928746',
    projectId: 'yampi-barberia',
    authDomain: 'yampi-barberia.firebaseapp.com',
    storageBucket: 'yampi-barberia.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUgRDmd6cLDqYTsedO6Bs52Hma6PoPQ1E',
    appId: '1:838989928746:android:2446e2eb9bab9b54352653',
    messagingSenderId: '838989928746',
    projectId: 'yampi-barberia',
    storageBucket: 'yampi-barberia.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYWmrz5n9aFA4C9qOQustAPThtHc27mUc',
    appId: '1:838989928746:ios:533caa920d26fa6d352653',
    messagingSenderId: '838989928746',
    projectId: 'yampi-barberia',
    storageBucket: 'yampi-barberia.firebasestorage.app',
    iosBundleId: 'com.example.yampi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYWmrz5n9aFA4C9qOQustAPThtHc27mUc',
    appId: '1:838989928746:ios:533caa920d26fa6d352653',
    messagingSenderId: '838989928746',
    projectId: 'yampi-barberia',
    storageBucket: 'yampi-barberia.firebasestorage.app',
    iosBundleId: 'com.example.yampi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDR5-Fn4x6fbD2-JuNBuJ2BSXKJwSMxFT4',
    appId: '1:838989928746:web:835661795bc5850a352653',
    messagingSenderId: '838989928746',
    projectId: 'yampi-barberia',
    authDomain: 'yampi-barberia.firebaseapp.com',
    storageBucket: 'yampi-barberia.firebasestorage.app',
  );
}
